pieza(reina).
pieza(rey).
pieza(alfil).
pieza(peon).
pieza(torre).
pieza(caballo).
casilla(a).
tablero(b).
valor_pieza(nueve_puntos,reina).
valor_pieza(cinco_puntos,torre).
valor_pieza(tres_puntos,alfil).
valor_pieza(tres_puntos,caballo).
valor_pieza(un_puntos,peon).
se_puede_mover(peon,una_casilla).
se_puede_mover(reina,varias_casillas).
se_puede_mover(rey,una_casilla).
se_puede_mover(torre,varias_casillas).
se_puede_mover(alfil,varias_casillas).
se_puede_mover(caballo,varias_casillas).
se_puede_mover(caballo,saltar_pieza).
puede_comer(peon,de_manera_diagonal).
puede_comer(alfil,de_manera_diagonal).
puede_comer(caballo,casilla_desplza).
puede_comer(torre,de_manera_horizontal).
puede_comer(torre,de_manera_vertical).
puede_comer(reina,de_manera_vertical).
puede_comer(reina,de_manera_horizontal).
puede_comer(reina,de_manera_diagonal).
puede_comer(rey,de_manera_horizontal).
puede_comer(rey,de_manera_vertical).
puede_comer(rey,de_manera_diagonal).
se_mueve(reina,mov_diagonal).
se_mueve(reina,mov_vertical).
se_mueve(reina,mov_horizontal).
se_mueve(peon,mov_vertical).
se_mueve(torre,mov_vertical).
se_mueve(torre,mov_horizontal).
se_mueve(alfil,mov_diagonal).
enroque(X,Y):-pieza(X),pieza(Y),se_mueve(X,mov_vertical),se_mueve(X,mov_horizontal),se_mueve(Y,mov_vertical),se_mueve(Y,mov_horizontal),se_puede_mover().
caracteristicas(X,Y):-valor_pieza(X,Y);se_puede_mover(Y,X);puede_comer(Y,X).
es_reina(X):-pieza(X),se_mueve(X,(mov_diagonal;mov_horizontal;mov_vertical)),valor_pieza(nueve_puntos,X),se_puede_mover(X,varias_casillas),
puede_comer(X,(de_manera_horizontal;de_manera_diagonal;de_manera_vertical)).
es_alfil(X):-pieza(X),se_mueve(X,mov_diagonal),valor_pieza(tres_puntos,X),se_puede_mover(X,varias_casillas),puede_comer(X,de_manera_diagonal).
es_peon(X):-pieza(X),se_mueve(X,mov_vertical),valor_pieza(un_punto,X),se_puede_mover(X,una_casilla),puede_comer(X,de_manera_diagonal).
es_torre(X):-pieza(X),se_mueve(X,mov_vertical),se_puede_mover(X,mov_horizontal),valor_pieza(cinco_puntos,X),se_pude_mover(X,varias_casillas),puede_comer(X,de_manera_vertical),puede_comer(X,de_manera_horizontal).